//farmer, the taj mahal, doctor, sun, a ckass picnin, a visit to zoo
// my country, my fav game, first day at school, teachers day
const paragraphs = [
    'India is an agricultural country. Most of the people live in villages and are farmers. They grow cereals, pulses, vegetables and fruits. The farmers lead a tough life. They get up early in the morning and go to the fields. They stay and work on the farm late till evening. The farmers usually live in kuchcha houses. Though, they work hard they remain poor. Farmers eat simple food; wear simple clothes and rear animals like cows, buffaloes and oxen. Without them there would be no cereals for us to eat. They play an important role in the growth and economy of a country.',
    'The Taj Mahal is a beautiful monument built in 1631 by an Emperor named Shah Jahan in memory of his wife Mumtaz Mahal. It is situated on the banks of river Yamuna at Agra. It looks beautiful in the moonlight. The Taj Mahal is made up of white marble. In front of the monument, there is a beautiful garden known as the Charbagh. Inside the monument, there are two tombs. These tombs are of Shah Jahan and his wife Mumtaz Mahal. The Taj Mahal is considered as one of the Seven Wonders of the World. Many tourists come to see this beautiful structure from different parts of the world.',
    'The doctor is a person who looks after the sick people and prescribes medicines so that the patient recovers fast. In order to become a doctor, a person has to study medicine. Doctors lead a hard life. Their life is very busy. They get up early in the morning and go to the hospital. They work without taking a break. They always remain polite so that patients feel comfortable with them. Since doctors work so hard we must realise their value.',
    'The sun is a huge ball of gases. It has a diameter of 1,392,000 km. It is so huge that it can hold millions of planets inside it. The Sun is mainly made up of hydrogen and helium gas. The surface of the Sun is known as the photosphere. The photosphere is surrounded by a thin layer of gas known as the chromospheres. Without the Sun, there would be no life on Earth. There would be no plants, no animals and no human beings. As, all the living things on Earth get their energy from the Sun for their survival.',
    'I am Nidhi Tuli. I study in Class IV, Lawrence School, and Delhi. Last month, my class went for a picnic to Badkal Lake. There were about sixty students and five teachers. We took eatables and drinks with us. We boarded the bus at around eight ‘o’clock in the morning. As the bus moved, we all clapped and shouted with joy. We sang songs and played games on the way. We reached the picnic spot at ten ‘o’clock. We, all along with our teachers went near the ake. Many people were boating in the lake. We also hired boats and went for boating. We enjoyed a lot over there. At one ‘o’clock we had our lunch. After taking lunch we played games and shared jokes with each other. Around four ‘o’clock in the evening, we left the picnic spot. At about six ‘o’clock in the evening we reached our school. Even today, I remember that wonderful day.',
    'Last Sunday, I went along with my friends to a zoo. It is located near Purana Quila in Delhi. It is one of the biggest in India. There were many beautiful birds, monkeys, lions, tigers, cheetahs and snakes in the zoo. Apart from big animals, there were different types of colourful birds in the zoo. The wild and dangerous animals like lions, tigers and cheetahs were kept in different cages. We even saw a white tiger and a gorilla in the zoo. Some of the animals were relaxing while some of them were eating their food. We enjoyed seeing the acrobatics of the monkeys. I gave some peanuts and bananas to them. Then, we went for an elephant ride. We enjoyed the ride a lot. It was fun.',
    'My name is Anupam Rastogi. I love my country India very much. It has many beautiful mountains, lakes, rivers and deserts. It is the seventh largest country in the world. The river Ganga is one of the most holy rivers of India. In India, people of different religions live and speak different languages. It has many cultures and traditions. It is the birthplace of many great Gods like Lord Rama, Lord Krishna, Lord Buddha, Lord Mahavira and Guru Nanak Dev. Apart from this, many great leaders like, Rani Laxmi Bai, Bhagat Singh, Mahatama Gandhi, Subhash Chandra Bose and Jawahar Lai Nehru were also born in India. I feel proud that I am an Indian. I love my country.',
    'I am Rohit. I study in Class IY St. Xaviers School, Delhi. My favourite game is cricket. This game was played for the first time in England. Then, it spread to different countries like India, Pakistan, Australia, South Africa, New Zealand, Kenya, Bangladesh and many other countries. All the countries have their own team. In cricket, there are eleven players with a captain and a vice-captain in each team. In cricket, two types of matches are played. One is the test match and the other is the one day match. Each team plays 50 overs. Each over has six balls. The captain of each team decides whether he’ll bowl or bat first. I really love to see all the matches on the television. Dhoni is my favourite cricket player. He is an excellent player.',
    'I am Chintoo Singh. I study in Class III. I love my school very much. I still remember my first day in the school. I was very small at that time. My mother took me to Nursery I. The name of my school was Sapphire International School. It was a very beautiful school. My principal took me to the class. Her name was Mrs. Rachna Mishra. She was very sweet and kind to me. She used to give me toffees everyday. My class teacher’s name was Payal Sehgal. She used to love me a lot. I cried a lot on the first day but my teacher gave me a lot of toys. She took me to the ball pool where I played a lot.',
    'Teachers’ day in India is celebrated on September 5th every year. It is the birthday of the second President of India, Dr. Sarvepalli Radhakrishnan, a literary scholar and a great teacher. It was in his honour, that this day was declared as Teachers’ Day. It is a day to have fun with our teachers. In most schools students relax with their teachers and cultural programmes are organised for the teachers in the school. Students give cards flowers and gifts to their teachers play an important role in students’ life and the lessons taught by our teachers remain with the students throughout their lives. Teachers, who spend their lives teaching kids, do more than just to teach. They help the students shape the future of their community’s cities and countries.'
]